### ISSUE TITLE
ERR#0015: error 403, try again later

### ISSUE THREAD

**Issue by optimvsjag** [JavierCastilloGuillen/Screener_Argentina#1]
Hi Javier,

Looks like investpy not runs ok for this import data. I've this error code "investpy\stocks.py", line 1495, in get_stocks_overview
    raise ConnectionError(ConnectionError: ERR#0015: error 403, try again later."

Looking for I find this issue open in the investpy library but is not solved. So I can't test your great screener and apply some changes to make my screener. https://github.com/alvarobartt/investpy/issues/600

In your youtube tutorial you used the yahoo finance import data, but in this code we have investpy. Should we change to yahoo finance again? How we can update this code to make it functional?

Thanks a lot for your great job to the community.

**Comment by JavierCastilloGuillen** [comment]
This problem about data extraction has been discussed [here](https://github.com/alvarobartt/investpy/issues/613). 
Needs to get another datasource library. In the Investpy package recommends investiny, but any other will work, as long as it has the same data structure, the screener should work fine. 

Bear in mind this was an example from time ago and the code might need updates and modifications to meet your needs. The example was just a structure for further development.
